### PR TITLE
[WIP] detailed exception handling for the api/projects POST method

### PR DESCRIPTION
**Pull request by henderkes**
I'm not sure if returning a tuple of (list(ids), list(ApiException)) is best design but couldn't come up with a better idea quickly.
What exactly did you have in mind @markwitz ?
This references Issue #82

### CODE REVIEW

**Comment by DubbleClick** [comment]
This references Issue #82 
Travis fails because the method no longer returns a list of uuid4's

**Comment by henderkes** [comment]
Sorry, attempted Rebasing in Visual Studio, the result code is correct but it kind of changed from newmaster->oldmaster->oldmaster->...->newmaster

**Comment by Drakulix** [comment]
This brings up the discussion of how we want to handle one out of multiple failing. To be honest I don't like this approach of "some" success. If one fails, all should fail.

**Comment by henderkes** [comment]
in that case we'd have to delete the successfully created projects once one fails and return the project that we couldn't create. ideas?

**Comment by Drakulix** [comment]
I would do all validation at the beginning and then hope mongodb insert does not fail. If it does we sure would need to "try" to delete just every project

**Comment by henderkes** [comment]
that's exactly what we had before

**Comment by Drakulix** [comment]
Not really, since we still can have multiple failing on the validation phase.

**Comment by henderkes** [comment]
```
try:
        is_valid = validator.is_valid(manifest)
        if is_valid: ...
        else:
            build and raise apiexception
```

^ The raised ApiException should entail that information unless I am mistaken

**Comment by Drakulix** [comment]
Well then I don't get what @markwitz wanted with issue #82

**Comment by henderkes** [comment]
yeah this was my first take on what he could have meant with it

**Comment by markwitz** [comment]
I had problems identifying which project in the list failed. I could imagine someone uploading like 20 projects at once and 3 of them failing in different points at the moment it will be quite hard to figure out wich one failed and where. 

I'm totally with Drakulix that we should first validate all manifests and return an error if the validation failed. But it should be made easier to figure out which one failed. We could validate one manifest after the other and give a list oft errors and successful validations. So every item in the list has its own error msg. That would make reading much easier.

**Comment by markwitz** [comment]
I looked a little more in to in and right now if the validation is failing it should fail for all items in the manifest:
`try:
        is_valid = validator.is_valid(manifest)

        if is_valid:
                      ....
`
so we're good here. Im only complaining that the error msg displayed is confusing and should be made simpler but that task isn't that important and we should focus on other things. So maybe move this to the backlog? @Drakulix 
I will poste the output here in a second:

**Comment by henderkes** [comment]
that's however an enhancement to the validator, not an issue with the (original) /api/projects POST method
when I started writing the method we had a discussion on how the case of multiple files should be validated and we agreed on giving the manifest array to the validator, not to iterate through projects in the POST method.

in that case, this PR can be closed as the changes are irrelevant

**Comment by markwitz** [comment]
`{
  "message": "Validation Error: \nFalse",
  "validation_error": {
    "errors": [
      "[{'title': 'test_project0', 'url': ['www.github.com/knex/'], 'analysis': [{'url': 'here-you-find-the-analysis.com', 'description': 'thats what this analysis is about'}], 'authors': [{'name': 'test_owner0', 'email': 'email@address.com'}], 'team': {'team_name': 'teamname'}, 'status': 'DONE', 'description': 'can this be a multiline description?', 'date_creation': '1970-01-01', 'date_last_updated': '2017-05-11', 'tags': ['tag', 'bio'], 'future_work': 'this is something related to this work', 'related_projects': [{'id': 0, 'name': 'name of the listed project', 'author': 'author', 'url': 'www.my.url'}]}, {'title': 'test_project0', 'url': ['www.github.com/knex/'], 'analysis': [{'url': 'here-you-find-the-analysis.com', 'description': 'thats what this analysis is about'}], 'authors': [{'name': 'test_owner0', 'email': 'email@address.com'}], 'team': {'team_name': 'teamname'}, 'status': 'DONE', 'description': 'can this be a multiline description?', 'date_creation': '1970-01-01', 'date_last_updated': '2017-05-11', 'tags': ['tag', 'bio'], 'future_work': 'this is something related to this work', 'related_projects': [{'id': 0, 'name': 'name of the listed project', 'author': 'author', 'url': 'www.my.url'}]}, {'titledfdf': 'test_project0', 'url': ['www.github.com/knex/'], 'analysis': [{'url': 'here-you-find-the-analysis.com', 'description': 'thats what this analysis is about'}], 'authors': [{'name': 'test_owner0', 'email': 'email@address.com'}], 'team': {'team_name': 'teamname'}, 'status': 'DONE', 'description': 'can this be a multiline description?', 'date_creation': '1970-01-01', 'date_last_updated': '2017-05-11', 'tags': ['tag', 'bio'], 'future_work': 'this is something related to this work', 'related_projects': [{'id': 0, 'name': 'name of the listed project', 'author': 'author', 'url': 'www.my.url'}]}, {'title': 'test_project0', 'url': ['www.github.com/knex/'], 'analysis': [{'url': 'here-you-find-the-analysis.com', 'description': 'thats what this analysis is about'}], 'authors': [{'name': 'test_owner0', 'email': 'email@address.com'}], 'team': {'team_name': 'teamname'}, 'status': 'DONE', 'description': 'can this be a multiline description?', 'date_creation': '1970-01-01', 'date_last_updated': '2017-05-11', 'tags': ['tag', 'bio'], 'future_work': 'this is something related to this work', 'related_projects': [{'id': 0, 'name': 'name of the listed project', 'author': 'author', 'url': 'www.my.url'}]}] is not valid under any of the given schemas"
    ],
    "sub_errors": [
      "Additional properties are not allowed ('titledfdf' was unexpected)",
      "'title' is a required property",
      "[{'title': 'test_project0', 'url': ['www.github.com/knex/'], 'analysis': [{'url': 'here-you-find-the-analysis.com', 'description': 'thats what this analysis is about'}], 'authors': [{'name': 'test_owner0', 'email': 'email@address.com'}], 'team': {'team_name': 'teamname'}, 'status': 'DONE', 'description': 'can this be a multiline description?', 'date_creation': '1970-01-01', 'date_last_updated': '2017-05-11', 'tags': ['tag', 'bio'], 'future_work': 'this is something related to this work', 'related_projects': [{'id': 0, 'name': 'name of the listed project', 'author': 'author', 'url': 'www.my.url'}]}, {'title': 'test_project0', 'url': ['www.github.com/knex/'], 'analysis': [{'url': 'here-you-find-the-analysis.com', 'description': 'thats what this analysis is about'}], 'authors': [{'name': 'test_owner0', 'email': 'email@address.com'}], 'team': {'team_name': 'teamname'}, 'status': 'DONE', 'description': 'can this be a multiline description?', 'date_creation': '1970-01-01', 'date_last_updated': '2017-05-11', 'tags': ['tag', 'bio'], 'future_work': 'this is something related to this work', 'related_projects': [{'id': 0, 'name': 'name of the listed project', 'author': 'author', 'url': 'www.my.url'}]}, {'titledfdf': 'test_project0', 'url': ['www.github.com/knex/'], 'analysis': [{'url': 'here-you-find-the-analysis.com', 'description': 'thats what this analysis is about'}], 'authors': [{'name': 'test_owner0', 'email': 'email@address.com'}], 'team': {'team_name': 'teamname'}, 'status': 'DONE', 'description': 'can this be a multiline description?', 'date_creation': '1970-01-01', 'date_last_updated': '2017-05-11', 'tags': ['tag', 'bio'], 'future_work': 'this is something related to this work', 'related_projects': [{'id': 0, 'name': 'name of the listed project', 'author': 'author', 'url': 'www.my.url'}]}, {'title': 'test_project0', 'url': ['www.github.com/knex/'], 'analysis': [{'url': 'here-you-find-the-analysis.com', 'description': 'thats what this analysis is about'}], 'authors': [{'name': 'test_owner0', 'email': 'email@address.com'}], 'team': {'team_name': 'teamname'}, 'status': 'DONE', 'description': 'can this be a multiline description?', 'date_creation': '1970-01-01', 'date_last_updated': '2017-05-11', 'tags': ['tag', 'bio'], 'future_work': 'this is something related to this work', 'related_projects': [{'id': 0, 'name': 'name of the listed project', 'author': 'author', 'url': 'www.my.url'}]}] is not of type 'object'"
    ]
  }
}`

**Comment by markwitz** [comment]
its still about how to pass the exception so i think its an issue of the post method

**Comment by henderkes** [comment]
now I understand, that's part of @Krisselchen s exception initialization

**Comment by henderkes** [comment]
The issue however still is the exception is_valid raises. The error message is **{json}** is not valid under any of the given schemas. Suberror messages are [ "Additional properties are not allowed ('titledfdf' was unexpected)", "'title' is a required property", **{json}** is not of type 'object'.

What do we do here?

**Comment by henderkes** [comment]
http://python-jsonschema.readthedocs.io/en/latest/errors/

says:

> message
>    A human readable message explaining the error.


but that's exactly our issue.

**Comment by markwitz** [comment]
i think this would be much easier to read if it would be easy to figure out which manifest failed but i already said that.

**Comment by henderkes** [comment]
yes, but the issue is the error.message the Draft4Validator produces, not how it is handled in the POST method. I can currently not think of an easy way to make this more readable, unless manually parsing and rewriting the error message the validator gives us...

**Comment by henderkes** [comment]
any ideas?

**Comment by markwitz** [comment]
the only thing i can think of is trying to list suberrors with an identifyer which references the manifest that created the error of go back to only validating one manifest at a time and do not let the validator do that work for us by validating a list of manifests. don't realy know how to discribe that right now Trying to edit this tomorrow.

**Comment by henderkes** [comment]
I understand what you mean, that way we could probably cut the json part out of it (string editing) and replace it with the index of the manifest.

Not a very elegant solution code wise, but probably better than what the validator gives us right now...

**Pull request closed without merging**
