### PR TITLE
Add offline dependencies

### PR DESCRIPTION
**Pull request by Rintel**
# What?
- Added boostrap offline support 
- Added material-icon offline support
- Added roboto font offline support 

I know, these are a fucking lot of lines. Sorry but not sorry. Now we have the wanted offline support.

### CODE REVIEW

**Comment by henderkes** [comment]
Main page request is crashing again, I guess it can't find the static file

**Comment by Rintel** [comment]
wtf, I'm just referecing to the local dependencies, I really don't know what's the reason for this right know.

**Comment by henderkes** [comment]
I have no idea, @mharasic ?

Nope... But I will try to check it these days

**Comment by mharasic** [comment]
No idea... I will check it

**Pull request closed without merging**
