### PR TITLE
added support for array of json objects in request.json/request.data

### PR DESCRIPTION
**Pull request by henderkes**

### CODE REVIEW

**Comment by Drakulix** [comment]
I assume this is fixing #82. Why did you not assign yourself to that issue, if you started solving it? I gave this task to @pdler for that reason...

**Comment by pdler** [comment]
Yes, looks like this..

**Comment by henderkes** [comment]
I've actually been looking for that issue but haven't been able to find it, sorry.

**Review by Drakulix — APPROVED** [review]
Well there is no point in *not* merging it...

**Pull request merged**
